pub const WabtFeatures = extern struct {};

pub extern fn wabt_new_features() *WabtFeatures;
pub extern fn wabt_destroy_features(features: *WabtFeatures) void;
pub extern fn wabt_exceptions_enabled(features: *WabtFeatures) bool;
pub extern fn wabt_set_exceptions_enabled(features: *WabtFeatures, enabled: c_int) void;
pub extern fn wabt_mutable_globals_enabled(features: *WabtFeatures) bool;
pub extern fn wabt_set_mutable_globals_enabled(features: *WabtFeatures, enabled: c_int) void;
pub extern fn wabt_sat_float_to_int_enabled(features: *WabtFeatures) bool;
pub extern fn wabt_set_sat_float_to_int_enabled(features: *WabtFeatures, enabled: c_int) void;
pub extern fn wabt_sign_extension_enabled(features: *WabtFeatures) bool;
pub extern fn wabt_set_sign_extension_enabled(features: *WabtFeatures, enabled: c_int) void;
pub extern fn wabt_simd_enabled(features: *WabtFeatures) bool;
pub extern fn wabt_set_simd_enabled(features: *WabtFeatures, enabled: c_int) void;
pub extern fn wabt_threads_enabled(features: *WabtFeatures) bool;
pub extern fn wabt_set_threads_enabled(features: *WabtFeatures, enabled: c_int) void;
pub extern fn wabt_function_references_enabled(features: *WabtFeatures) bool;
pub extern fn wabt_set_function_references_enabled(features: *WabtFeatures, enabled: c_int) void;
pub extern fn wabt_multi_value_enabled(features: *WabtFeatures) bool;
pub extern fn wabt_set_multi_value_enabled(features: *WabtFeatures, enabled: c_int) void;
pub extern fn wabt_tail_call_enabled(features: *WabtFeatures) bool;
pub extern fn wabt_set_tail_call_enabled(features: *WabtFeatures, enabled: c_int) void;
pub extern fn wabt_bulk_memory_enabled(features: *WabtFeatures) bool;
pub extern fn wabt_set_bulk_memory_enabled(features: *WabtFeatures, enabled: c_int) void;
pub extern fn wabt_reference_types_enabled(features: *WabtFeatures) bool;
pub extern fn wabt_set_reference_types_enabled(features: *WabtFeatures, enabled: c_int) void;
pub extern fn wabt_annotations_enabled(features: *WabtFeatures) bool;
pub extern fn wabt_set_annotations_enabled(features: *WabtFeatures, enabled: c_int) void;
pub extern fn wabt_code_metadata_enabled(features: *WabtFeatures) bool;
pub extern fn wabt_set_code_metadata_enabled(features: *WabtFeatures, enabled: c_int) void;
pub extern fn wabt_gc_enabled(features: *WabtFeatures) bool;
pub extern fn wabt_set_gc_enabled(features: *WabtFeatures, enabled: c_int) void;
pub extern fn wabt_memory64_enabled(features: *WabtFeatures) bool;
pub extern fn wabt_set_memory64_enabled(features: *WabtFeatures, enabled: c_int) void;
pub extern fn wabt_multi_memory_enabled(features: *WabtFeatures) bool;
pub extern fn wabt_set_multi_memory_enabled(features: *WabtFeatures, enabled: c_int) void;
pub extern fn wabt_extended_const_enabled(features: *WabtFeatures) bool;
pub extern fn wabt_set_extended_const_enabled(features: *WabtFeatures, enabled: c_int) void;
pub extern fn wabt_relaxed_simd_enabled(features: *WabtFeatures) bool;
pub extern fn wabt_set_relaxed_simd_enabled(features: *WabtFeatures, enabled: c_int) void;
