name: zig fmt
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  fmt:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
      - name: format check
        run: zig fmt --check src build.zig
