name: zig build test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: goto-bus-stop/setup-zig@v2
      - uses: lukka/get-cmake@latest
      - uses: egor-tensin/setup-clang@v1
        with:
          version: 16
      - name: test
        run: make test
